#include <stdio.h>
#include <string.h>
//These two help with generating a random number. We take a seed from time.h to be used in the random function in stdlib
#include <stdlib.h>
#include <time.h>
#include <ctype.h>

//TODO: 1.Validate User inputs:We need to make sure the user only enters valid characters a-z.
//TODO: 2.Reduce the string to lower. Use string.h functions
//TODO: MOONS. Suits- Keep the arrays contents to check if there is a more fitting word. //First only check if the position is an exact match.


//timing tells the score. Slabs.
//Interface-GUI: Windows.h - borrow all gta files.
//GTK

//Helps find the total number of lines by seeing how many times it has to run through \n. 
//It limits the total lines to 5000 as otherwise it kept on going for some reason. Besides that 5000 gives a good variety of words
//You can adjust the total number of words it can take.
int totallines(FILE *fp){
	int tot=0;
	int c=1;
	int i=0;
	//Makes sure that fp isn't null, that feof isn't reached, the third condition is additional and just an extra precaution. 
	//The forth limits the pool of words
	while (fp!=NULL && feof(fp)==0 && c!=EOF){
		//Takes it character by character
		for (c=getc(fp);(c!='\n') && (c!=EOF);c=getc(fp));
		tot+=1;
	}
	//Helps return the file back to the beginning
	rewind(fp);
	return tot;
}


//Sets the text color with these 4.

void yellow(){
	printf("\033[0;33m");
}

void green(){
	printf("\033[0;32m");
}

void grey(){
	printf("\e[38;5;248m");
}

void white(){
	printf("\033[0m");
}

//Helps get the word

void getword(FILE *fp, char *st, int n){
	//Takes the Uses the total lines function in random number generation. As the random number can be practically anything it is 
	//divided by modulous of the total number of lines +1 to count the last value to as num%n gives a range from 0 to (num-1)
	int tot=totallines(fp);
	int linenum=(rand()) % (tot+1);
	//Adds to account for a space at the end of the words and '\n'. n is the number of letters in the word.
	//Here it is 5 by default but if we want to add features we can more easily do for 6.
	int mult=n+2;
	//Multiplies the line number generated by the multiplier from the start of the file to find the word.
	fseek(fp,linenum*mult,SEEK_SET);
	char c;
	int count=0;
	for (c=fgetc(fp);c!='\n';c=fgetc(fp)){
		*(st+count)=c;
		count++;
	}
	*(st+n)='\0';
}

// Convert string to lowercase
void to_lowercase(char *str) {
	for (int i = 0; str[i]; i++) {
		str[i] = tolower((unsigned char) str[i]);
	}
}

// Validate input (only a-z or A-Z)
int is_valid_input(const char *input, int len) {
	for (int i = 0; i < len; i++) {
		if (!isalpha(input[i])) return 0;
	}
	return 1;
}

void guess(char *userword, int n){
	int i;
	printf("If you enter more than 5 letters only the first five will be taken.Enter your guess:\n");
	//First initializes everything to ' ' to avoid errors
	for (i=0;i<n;i++){
		*(userword+i)=' ';
	}
	//Takes user input and limits it to 5 characters. Could use validation to remove numbers
	int valid=0;
	while (!valid){
		scanf("%5s",userword);
		fflush(stdin);
		to_lowercase(userword);
		valid=(is_valid_input(userword,5));
		if (!valid){
			printf("Only alphabets (a-z) and (A-Z) are accepted!Re-nter your guess:\n");
		}
	}
	
	//adds a terminating character at the end
	*(userword+n)='\0';
	//for testing purposes.
}

int check(char userword[], char st[], int n){
	int cor=0;
	int i;
	char temp[7];
	//Uses a temporary array for the main word.
	for (i=0;i<n;i++){
		*(temp+i)=*(st+i);
	}
	int f;
	int j;
	char colors[7];
	for (i=0;i<n;i++){
		f=1;
		for (j=0;j<n;j++){
			if (*(userword+i)==*(temp+j) && i==j){
				cor++;
				f=0;
				*(colors+i)='g';
				*(temp+j)=' ';
				break;
				/*if (i==j){
					//colors it green if the positions match
					cor++;
					green();
				}
				else{
					//otherwise yellow.
					yellow();
				}
				putchar(*(temp+j));
				//sets back to default white at the end.
				white();
				*(temp+j)=' ';
				f=0;
				break;*/
			}
		}
		if (f){
			for (j=0;j<n;j++){
				if (*(userword+i)==*(temp+j)){
					*(colors+i)='y';
					*(temp+j)=' '; 
					break;
			
				}
			}
		//If it's not in the word the character is just printed out.
		}
	}	
	for (j=0;j<n;j++){
		if (*(colors+j)=='g'){
			green();
		}		
		else{
			if (*(colors+j)=='y'){
				yellow();
			}
		}	
		putchar(*(userword+j));
		white();

	}
	printf("\n");
	return cor;
}


void game(int n, int *points, int practice){
	FILE *fp=fopen("five.txt","r");

	char st[n+2];
	getword(fp,st,n);
	int excess_user=n*2;
	char userword[excess_user];
	int count=0;
	int l;
	//They both keep taking guesses till the user gets the right answer.
	//Only in practice mode you get unlimitted guesses.
	if (practice){
		guess(userword,n);
		while (check(userword, st, n)!=n){
			printf("\nTry Again!\n");
			count++;
			guess(userword,n);
		}
		printf("\nYou got the answer right in %d tries!\n",count);

	}
	else {
		for (count=0;count<n;count++){
			guess(userword,n);
			if (check(userword, st, n)==n){
				printf("\nYou got the answer right!\n");
				l=count;
				break;
			}
		}
	}
	//Point system
	if (practice){
			printf("You won 10 points!\n"); 
			*points+=10; //Incorporate time to the points system
	}
	else{
		switch (l){
			case 0:printf("You won a 100 points!\n"); *points+=100; break;
			case 1:printf("You won 50 points!\n"); *points+=50; break;
			case 2:printf("You won 40 points!\n"); *points+=40; break;
			case 3:printf("You won 30 points!\n"); *points+=30; break;
			case 4:printf("You won 20 points!\n"); *points+=20; break;
			default:printf("Sorry but you lost! The word was supposed to be %s\n",st);
		}
	}
	fclose(fp);
}

int main(){
	srand(time(NULL));
	int points=0;
	char f=' ';
	char c=' ';
	while (c!='e' && c!='E'){
		c=' ';
		printf("Which mode would you like to pick? 5:Five Letter Mode, P:Practice mode\n");
		while (f!='5' && f!='P' && f!='p'){
			fflush(stdin);
			scanf("%c",&f);
			switch (f){
				case '5': game(5, &points, 0); break;
				case 'P': game(5, &points, 1);break;
				case 'p': game(5, &points, 1);break;
				default:printf("Re-enter mode type!");
			}
		}
		while (c!='c' && c!='C' && c!='e' && c!='E'){
			printf("\nWould you like to play once more? C for continue, E to end\n");
			scanf(" %c",&c);
			fflush(stdin);
			if (c!='c' && c!='C' && c!='e' && c!='E'){
				printf("Invalid input. Try again!\n");
			}
		}
		f=' ';
	}
	printf("You won a total of %d points!",points);
	return 0;
}